Add spacing between inputs in Investor SAFT setup Step 4
glifio/wallet pull request #575
Opened 2020-09-23 14:06 UTC by as-dr

Added `16px` margin-top. 

Need to wait until the Ledger issues are fixed for me to eyeball it & confirm it's good.

2020-09-23 20:57 UTC, Schwartz10 requested changes
Just delete those comments and ping me when you make that commit

2020-09-23 20:57 UTC, Schwartz10 commented on components/Investor/Home.jsx
> +            // m='0'
@as-dr just delete things, no comments

2020-09-24 00:25 UTC, as-dr commented on components/Investor/Home.jsx
> +            // m='0'
@Schwartz10 Brain fart. Done.

2020-09-24 00:25 UTC, as-dr commented
@Schwartz10 Good to go

2020-09-24 00:49 UTC, Schwartz10 approved these changes

2020-09-24 00:50 UTC, merged